name: SuiteStay 

services:
  frontend:
    build:
      context: ./SuiteStay/frontend_Angular
    image: suitestay-frontend
    container_name: frontend-container
    ports:
      - "80:80"
    networks:
      - suiteStayNetwork

  backend:
    build:
      context: ./SuiteStay/backend_SpringBoot/suitestay-backend
    image: suitestay-backend # Specifies the image name
    container_name: backend-container  # Sets a specific container name
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/suitestay_db # Updated MySQL URL
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Reyeslocal123! # Make sure this matches the MySQL password
    depends_on:
      - mysql
    networks:
      - suiteStayNetwork

  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Reyeslocal123! # Corrected MySQL root password
      MYSQL_DATABASE: suitestay_db
    ports:
      - "3307:3306"
    networks:
      - suiteStayNetwork

networks:
  suiteStayNetwork:
    driver: bridge