#server:
##  port: 8080
##
##spring:
##  devtools:
##    restart:
##      enabled: true
##  datasource:
##    url: jdbc:h2:mem:SuiteStayDB
##    username: sa
##    password: sa
##    driver-class-name: org.h2.Driver
##  jpa:
##    hibernate:
##      ddl-auto: create-drop #create-drop
##      format_sql: true;
##
##    defer-datasource-initialization: true
##    show-sql: true #shows in the log
##  h2:
##    console:
##      enabled: true
##  sql:
##    init:
##      mode: always

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/suitestay_db #adjust url
    username: root #adjust root
    password: Reyeslocal123! # adjust password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # create-drop to reset database
      format_sql: true
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always